// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import {IVerifier} from "../contracts/IVerifier.sol";
import {ShieldedPool} from "../contracts/ShieldedPool.sol";
import {HonkVerifier} from "../circuits/verifier/Verifier.sol";

/// @title RealProof — verifier accepts a real Plonk proof
/// @notice End-to-end proof of life. A proof generated by `bb prove`
///         against a witness from `nargo execute` is accepted by the
///         on-chain HonkVerifier. Once green, the chain cutover from
///         MockVerifier to HonkVerifier is just `pool.setVerifier(honkAddr)`.
///
/// Fixture: privacy/circuits/transfer/target/proof_dir/proof
///   - generated by the laptop workflow in Prover.toml.example
///   - bb's output format prepends the public inputs as 32-byte
///     big-endian field elements before the proof bytes themselves
///   - we read the file via vm.readFileBinary and split off the
///     PUBLIC_INPUT_COUNT * 32 = 256 prefix
///
/// If the proof file is missing, the test skips with a clear message
/// (CI doesn't fail before the developer runs the laptop workflow).
contract RealProofTest is Test {
    HonkVerifier honk;
    ShieldedPool pool;

    /// Path is relative to the forge root (privacy/), and ffi/fs_permissions
    /// must allow reading from circuits/transfer/target/.
    string constant PROOF_PATH = "circuits/transfer/target/proof_dir/proof";

    /// bb's UltraHonk proof file format:
    ///   - 4-byte length prefix (header)
    ///   - 8 x 32-byte public inputs (the same ones we pass as bytes32[])
    ///   - 14080 bytes of actual proof (PROOF_SIZE = 440 field elements * 32)
    /// Total file size: 4 + 256 + 14080 = 14340 bytes.
    /// The HonkVerifier.verify() function takes only the 14080-byte proof
    /// (not the header, not the public inputs), with publicInputs[] passed
    /// separately.
    uint256 constant PUBLIC_INPUT_COUNT = 8;
    uint256 constant FILE_HEADER_BYTES = 4;
    uint256 constant PUBLIC_INPUT_PREFIX_BYTES = FILE_HEADER_BYTES + PUBLIC_INPUT_COUNT * 32;

    /// Expected output commitment from Prover.toml.example. Must match
    /// the Poseidon2 hash of the output note (0, 1e18, 12345, 67890).
    bytes32 constant EXPECTED_OUTPUT_COMMITMENT =
        0x22a22e1ee3f460e1666d51645455b97498f6e9cb95fbb7bea281f9c74c28facc;

    function setUp() public {
        honk = new HonkVerifier();
        pool = new ShieldedPool(address(honk), address(this));
    }

    /// Build the 8 public inputs we expect for this fixture.
    function _publicInputs() internal pure returns (bytes32[] memory) {
        bytes32[] memory p = new bytes32[](PUBLIC_INPUT_COUNT);
        p[0] = bytes32(uint256(0));                        // input_nullifier_0
        p[1] = bytes32(uint256(0));                        // input_nullifier_1
        p[2] = EXPECTED_OUTPUT_COMMITMENT;                 // output_commitment_0
        p[3] = bytes32(uint256(0));                        // output_commitment_1
        p[4] = bytes32(uint256(0));                        // merkle_root
        p[5] = bytes32(uint256(1_000_000_000_000_000_000)); // public_amount = 1e18
        p[6] = bytes32(uint256(0));                        // public_asset = native
        p[7] = bytes32(uint256(0));                        // public_recipient
        return p;
    }

    /// Try to read the proof file. Returns (true, contents) if it
    /// exists, (false, "") otherwise. We don't want a hard fail when
    /// CI runs before the developer has generated a proof on their
    /// laptop.
    function _tryLoadProof() internal view returns (bool, bytes memory) {
        try vm.readFileBinary(PROOF_PATH) returns (bytes memory raw) {
            return (true, raw);
        } catch {
            return (false, "");
        }
    }

    /// Strip the public-input prefix from bb's raw proof file.
    function _stripPrefix(bytes memory raw) internal pure returns (bytes memory) {
        require(raw.length > PUBLIC_INPUT_PREFIX_BYTES, "proof file too small");
        bytes memory out = new bytes(raw.length - PUBLIC_INPUT_PREFIX_BYTES);
        for (uint256 i = 0; i < out.length; ++i) {
            out[i] = raw[i + PUBLIC_INPUT_PREFIX_BYTES];
        }
        return out;
    }

    function test_RealProof_Verifies() public view {
        (bool found, bytes memory raw) = _tryLoadProof();
        if (!found) {
            console.log("SKIPPED: proof file not found at", PROOF_PATH);
            console.log("Run nargo execute + bb prove per Prover.toml.example");
            return;
        }

        // Strip bb's 4-byte length header + 8*32 public-input prefix.
        bytes memory proofBytes = _stripPrefix(raw);
        assertEq(proofBytes.length, 14080, "stripped proof must be 14080 bytes");

        bool ok = IVerifier(address(honk)).verify(proofBytes, _publicInputs());
        assertTrue(ok, "HonkVerifier rejected the real proof");
    }
}
